---
  - name: Configure Radius
    uri:
      url: https://{{ private_ip }}:8888/restconf/data/openconfig-system:system/aaa
      user: "{{ ansible_admin }}"
      password: "{{ ansible_ssh_pass }}"
      method: PATCH
      headers:
        Content-Type: application/yang-data+json
        Accept: application/yang-data+json
      force_basic_auth: true
      force: true
      status_code: 200,204
      return_content: true
      validate_certs: false
      body_format: json
      body: "{{ lookup('ansible.builtin.file', 'files/radius-auth.json') }}"
    register: Radius
