name: "irulescan"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - 'examples/big-ip-irules/**'
  pull_request:
    branches:
      - main
    paths: 
    - 'examples/big-ip-irules/**'

jobs:
  irulescan-action:
    runs-on: ubuntu-latest
    name: "irulescan"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run irulescan-action
        uses: simonkowallik/irulescan-action@main
        id: irulescan_action
        with:
          scandir: examples/big-ip-irules

      - name: Save irulescan results
        run: |
          cat << 'EOF' > irulescan_result.yaml
          ${{ steps.irulescan_action.outputs.result }}
          EOF

      - name: Get changed/new iRules
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          files: |
            **.tcl
            **.irule

      - name: Extract results for changed/new iRules
        uses: mikefarah/yq@master
        with:
          cmd: |
            for CHANGED_FILE in ${{ steps.changed-files.outputs.all_changed_files }}; do
              export IRULE=/$(basename $CHANGED_FILE)
              yq --no-doc \
                'with_entries(select(.key == env(IRULE))) | with_entries(select(.value | length > 0))' \
                irulescan_result.yaml \
                | grep -v '^{}$' >> filtered_results.yaml
            done
            exit 0;

      - name: Display results (detail)
        uses: mikefarah/yq@master
        with:
          cmd: |
            cat filtered_results.yaml | yq .

      - name: Create makrdown summary then fail on findings
        run: |
          echo '# irulescan findings' >> $GITHUB_STEP_SUMMARY
          echo '```yaml' >> $GITHUB_STEP_SUMMARY
          cat filtered_results.yaml >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          [[ -s filtered_results.yaml ]] || echo "exit 1 due to security findings" && exit 1
